 /*****
 * 模块初始化页面
 * 根据ID 拼接即可
 * ***/ 
HtmlUntil.init2couClass4Manager = function(id){
	
	var $this = $("#"+id);
	var buf = new StringBuffer();
	 
	buf.append(' <div style=" height: 500px;width:100%" id="cou-class-manage" class="container padding-no margin-no">                                            ');
	buf.append('   <div id="cou-class-manage-div" class="row  margin-no">                                                                                   ');
	buf.append('    <div id="cou-class-manager-tab-cname" class="col-xs-2">                                                                      ');
	buf.append('     <div id="cou-class-manager-tab-cname-title">                                                                                ');
	buf.append('      <p>我的班级</p>                                                                                                            ');
	buf.append('      <a class="cou-class-addclass">添加</a>                                                                                                                ');
	buf.append('     </div>                                                                                                                      ');
	buf.append('     <div id="cou-class-manager-tab-cname-body">                                                                                 ');
	buf.append('     </div>                                                                                                                      ');
	buf.append('    </div>                                                                                                                       ');
	buf.append('    <div id="cou-class-manager-tab-stu" class="col-xs-10">                                                                       ');
	buf.append('     <div id="cou-class-manager-tab-stu-title">                                                                                  ');
	buf.append('      <div id="cou-class-manager-tab-stu-title-left" class="float-left">                                                         ');
	buf.append('       <ul>                                                                                                                      ');
	buf.append('        <li id="cou-class-manager-tab-stu-model-add-btn"><i class="glyphicon glyphicon-plus-sign"></i>添加学生</li>              ');
	buf.append('        <li id="cou-class-manager-tab-stu-model-import4stu-btn"><i class="glyphicon glyphicon-education"></i>导入学生</li>       ');
	buf.append('        <li id="cou-class-manager-tab-stu-model-import4photo-btn"><i class="glyphicon glyphicon-user"></i>导入学生头像</li>      ');
	buf.append('        <li><i class="glyphicon glyphicon-credit-card"></i>导出学籍卡</li>                                                       ');
	buf.append('        <li><i class="glyphicon glyphicon-th-list"></i>导出初始账号</li>                                                         ');
	buf.append('       </ul>                                                                                                                     ');
	buf.append('      </div>                                                                                                                     ');
	buf.append('      <div id="cou-class-manager-tab-stu-title-right" class="float-right">                                                       ');
	buf.append('       <p><i class="glyphicon glyphicon-user"></i>协助管理</p>                                                                   ');
	buf.append('      </div>                                                                                                                     ');
	buf.append('     </div>                                                                                                                      ');
	buf.append('     <div id="cou-class-manager-tab-stu-body">                                                                                   ');
	buf.append('      <p id="cou-class-manager-tab-stu-body-table-info"> </p>                                                                    ');
	buf.append('      <table id="cou-class-manager-tab-stu-table"></table>                                                                       ');
	buf.append('     </div>                                                                                                                      ');
	buf.append('    </div>                                                                                                                       ');
	buf.append('   </div>                                                                                                                        ');
	buf.append('  </div>																														');				
	
	$this.html(buf.toString());
};


HtmlUntil.couClassTabCname4Manage= function(data) {
    var buf = new StringBuffer();

    for(var i=0;i<data.length;i++){
    	var obj = data[i];
        buf.append('    <div class="cou-class-manager-tab-cname-list cursor-p" cid="'+obj.cid+'">');
        buf.append('    <input type="text" value="'+obj.name+'" class="cou-class-manager-tab-cname-input  cursor-p bg-color-white" style="background: none" disabled>');
        buf.append('    <a class="cou-class-manager-tab-cname-set-btn display-none">设置</a>');
        buf.append('    <div class="cou-class-manager-tab-cname-set-detail  cursor-p display-none">');
        buf.append('    <a class="cou-class-manager-tab-cname-reset  cursor-p">修改信息</a>');
        buf.append('    <a class="cou-class-manager-tab-cname-set-delete  cursor-p">删除班级</a>');
        buf.append('    </div>');
        buf.append('    </div>');
    }
    
    return buf.toString();
};

HtmlUntil.couClassTab4Info4Manager=function(){
    var buf = new StringBuffer();
    buf.append('基础数学2016-01班,共有25名学生,14名男生,11名女生;2位辅导员');
    return buf.toString();
};
HtmlUntil.couClassTabStuModelImport4Photo4Manage= function(data) {
    var buf = new StringBuffer();

     buf.append(' <div class="modal-body">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-div">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-detail">');
     buf.append('   <h5>导入学生头像注意事项:</h5>');
     buf.append('   <p>1.建议用学生的2寸免冠照片,尺寸大于160*160,大小小于2M,png或jpg格式</p>');
     buf.append('   <p>2.照片的名字必须以学号进行命名</p>');
     buf.append('   </div>');
     buf.append('   <input type="file" id="cou-class-manager-tab-stu-model-add-select-file" style="display: none">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-select">');
     buf.append('   <input id="cou-class-manager-tab-stu-model-add-select-file-cover" class="form-control" type="text" placeholder="请选择要上传的照片:">');
     buf.append('   <button class="btn btn-abj-primary" id="cou-class-manager-tab-stu-model-add-select-file-btn"><i class="glyphicon glyphicon-folder-open"></i>文件选择</but');
     buf.append('   <div class="clear"></div>');
     buf.append('   </div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photos">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-top"><img src="../../resource/img/test/student_03.png"></div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-bot">60633</div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-delete"><i class="glyphicon glyphicon-exclamation-sign"></i></div>');
     buf.append('   </div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-top"></div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-bot"></div>');
     buf.append('   </div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-top"></div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-bot"></div>');
     buf.append('   </div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-top"></div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-bot"></div>');
     buf.append('   </div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-top"></div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-bot"></div>');
     buf.append('   </div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-top"></div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-bot"></div>');
     buf.append('   </div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-top"></div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-bot"></div>');
     buf.append('   </div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-top"></div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-bot"></div>');
     buf.append('   </div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-top"></div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-bot"></div>');
     buf.append('   </div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo">');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-top"></div>');
     buf.append('   <div class="cou-class-manager-tab-stu-model-add-photo-bot"></div>');
     buf.append('   </div>');
     buf.append('   <div class="clear"></div>');
     buf.append('   </div>');
     buf.append('   </div>');
     buf.append('   <div class="container-fluid confirm-div">');
     buf.append('   <div class="row popup-btn-div conduct-confirm-btn-div"><span class="btn btn-abj-primary btn-sub"> 提交</span> </div>');
     buf.append('   </div>');
     buf.append('   </div>');
    
    return buf.toString();
};

HtmlUntil.couClassTabStuModelImport4Stu4Manage= function(data) {
    var buf = new StringBuffer();

    buf.append('    <div class="modal-body">');
    buf.append('    <div class="cou-class-manager-tab-stu-model-import4stu-div">');
    buf.append('    <div class="cou-class-manager-tab-stu-model-import4stu-detail">');
    buf.append('    <h5>操作步骤</h5>');
    buf.append('    <p>1.下载&lt&lt学生批量导入模版&gt&gt</p>');
    buf.append('    <p>2.打开下载表,将对应字段信息输入或粘贴进本表,为保障粘贴信息被有效导入,请使用纯文本或数字</p>');
    buf.append('    <p>信息输入完毕,点击"文件"选择按钮,选择excel文档</p>');
    buf.append('    <p><a>立即下载&lt&lt学生批量导入模版&gt&gt</a></p>');
    buf.append('    </div>');
    buf.append('    <input type="file" id="cou-class-manager-tab-stu-model-import4stu-select-file" style="display: none">');
    buf.append('    <div class="cou-class-manager-tab-stu-model-import4stu-select">');
    buf.append('    <input id="cou-class-manager-tab-stu-model-import4stu-select-file-cover" class="form-control" type="text">');
    buf.append('    <button class="btn btn-abj-primary" id="cou-class-manager-tab-stu-model-import4stu-select-file-btn"><i class="glyphicon glyphicon-folder-open"></i>文件选择</button>');
    buf.append('    <div class="clear"></div>');
    buf.append('    </div>');
    buf.append('    </div>');
    buf.append('    <div class="container-fluid confirm-div">');
    buf.append('    <div class="row popup-btn-div conduct-confirm-btn-div"><span class="btn btn-abj-primary btn-sub"> 开始导入</span> </div>');
    buf.append('    </div>');
    buf.append('    </div>');


    return buf.toString();
};
HtmlUntil.couClassTabStuModelAdd4Manage= function(data) {
    var buf = new StringBuffer();

    buf.append('    <div class="modal-body">');
    buf.append('    <div class="cou-class-manager-tab-stu-model-modify-div">');
    buf.append('    <div class="row form-popup-md">');
    buf.append('    <div class="col-xs-6 row">');
    buf.append('    <div class="col-xs-4"><p><span class="font-color-red">*</span>学号:</p></div>');
    buf.append('    <div class="col-xs-8"><input class="form-control" type="text"></div>');
    buf.append('    </div>');
    buf.append('    <div class="col-xs-6">');
    buf.append('    <div class="col-xs-4"><p><span class="font-color-red">*</span>姓名:</p></div>');
    buf.append('    <div class="col-xs-8"><input class="form-control" type="text"></div>');
    buf.append('    </div>');
    buf.append('    </div>');
    buf.append('    <div class="row form-popup-md">');
    buf.append('    <div class="col-xs-6 row">');
    buf.append('    <div class="col-xs-4"><p><span class="font-color-red">*</span>性别:</p></div>');
    buf.append('    <div class="col-xs-8 modify-sex-select"><input type="radio" name="sex">男<input type="radio" name="sex">女</div>');
    buf.append('    </div>');
    buf.append('    <div class="col-xs-6">');
    buf.append('    <div class="col-xs-4"><p>出生年月:</p></div>');
    buf.append('    <div class="col-xs-8"><input class="form-control" type="text"></div>');
    buf.append('    </div>');
    buf.append('    </div>');
    buf.append('    <div class="row form-popup-md">');
    buf.append('    <div class="col-xs-6 row">');
    buf.append('    <div class="col-xs-4"><p>民族:</p></div>');
    buf.append('    <div class="col-xs-8 modify-sex-select"><select class="form-control">汉</select></div>');
    buf.append('    </div>');
    buf.append('    <div class="col-xs-6">');
    buf.append('    <div class="col-xs-4"><p>政治面貌:</p></div>');
    buf.append('    <div class="col-xs-8"><input class="form-control" type="text"></div>');
    buf.append('    </div>');
    buf.append('    </div>');
    buf.append('    <div class="row form-popup-md ">');
    buf.append('    <div class="col-xs-2">');
    buf.append('    </div>');
    buf.append('    <div class="col-xs-10 cou-class-manager-tab-stu-model-modify">');
    buf.append('    <input type="checkbox">贫困生');
    buf.append('    <input type="checkbox">孤残学生');
    buf.append('    <input type="checkbox">单亲家庭');
    buf.append('    <input type="checkbox">烈士子女');
    buf.append('    </div>');
    buf.append('    </div>');
    buf.append('    <div class="row form-popup-md">');
    buf.append('    <div class="col-xs-6 row">');
    buf.append('    <div class="col-xs-4"><p>身份证:</p></div>');
    buf.append('    <div class="col-xs-8 modify-sex-select"><input class="form-control" type="text"></div>');
    buf.append('    </div>');
    buf.append('    <div class="col-xs-6">');
    buf.append('    <div class="col-xs-4"><p>高考号:</p></div>');
    buf.append('    <div class="col-xs-8"><input class="form-control" type="text"></div>');
    buf.append('    </div>');
    buf.append('    </div>');
    buf.append('    <div class="row form-popup-md">');
    buf.append('    <div class="col-xs-6 row">');
    buf.append('    <div class="col-xs-4"><p>手机:</p></div>');
    buf.append('    <div class="col-xs-8 modify-sex-select"><input class="form-control" type="text"></div>');
    buf.append('    </div>');
    buf.append('    <div class="col-xs-6">');
    buf.append('    <div class="col-xs-4"><p>短号:</p></div>');
    buf.append('    <div class="col-xs-8"><input class="form-control" type="text"></div>');
    buf.append('    </div>');
    buf.append('    </div>');
    buf.append('    <div class="row form-popup-md">');
    buf.append('    <div class="col-xs-6 row">');
    buf.append('    <div class="col-xs-4"><p>QQ号:</p></div>');
    buf.append('    <div class="col-xs-8 modify-sex-select"><input class="form-control" type="text"></div>');
    buf.append('    </div>');
    buf.append('    <div class="col-xs-6">');
    buf.append('    <div class="col-xs-4"><p>家长姓名:</p></div>');
    buf.append('    <div class="col-xs-8"><input class="form-control" type="text"></div>');
    buf.append('    </div>');
    buf.append('    </div>');
    buf.append('    <div class="row form-popup-md">');
    buf.append('    <div class="col-xs-6 row">');
    buf.append('    <div class="col-xs-4"><p>邮政编码:</p></div>');
    buf.append('    <div class="col-xs-8 modify-sex-select"><input class="form-control" type="text"></div>');
    buf.append('    </div>');
    buf.append('    <div class="col-xs-6">');
    buf.append('    <div class="col-xs-4"><p>家庭经济:</p></div>');
    buf.append('    <div class="col-xs-8"><select class="form-control"></select></div>');
    buf.append('    </div>');
    buf.append('    </div>');
    buf.append('    <div class="row form-popup-md ">');
    buf.append('    <div class="col-xs-2">');
    buf.append('    <p>籍贯:</p>');
    buf.append('    </div>');
    buf.append('    <div class="col-xs-10 cou-class-manager-tab-stu-model-modify">');
    buf.append('    <input class="form-control" type="text" style="width:409px;">');
    buf.append('    </div>');
    buf.append('    </div>');
    buf.append('    <div class="row form-popup-md ">');
    buf.append('    <div class="col-xs-2"  style="padding-right:14px;">');
    buf.append('    <p>家庭住址:</p>');
    buf.append('    </div>');
    buf.append('    <div class="col-xs-10 cou-class-manager-tab-stu-model-modify">');
    buf.append('    <input class="form-control" type="text" style="width:409px;">');
    buf.append('    </div>');
    buf.append('    </div>');
    buf.append('    </div>');
    buf.append('    <div class="container-fluid confirm-div">');
    buf.append('    <div class="row popup-btn-div conduct-confirm-btn-div"><span class="btn btn-abj-primary btn-sub"> 提交</span> </div>');
    buf.append('    </div>');
    buf.append('    </div>');
    
    return buf.toString();
};

HtmlUntil.couClassHelp4Manage = function(data){
	var buf = new StringBuffer();
	
	buf.append(' <div class="container width-full bg-color-class">                         ' );
	buf.append('   <div class="col-xs-5">                                                  ' );
	buf.append('    <div class="padding-md font-size-21 font-weight-bold">                 ' );
	buf.append('     我的同事                                                              ' );
	buf.append('    </div>                                                                 ' );
	buf.append('    <div class="bg-color-white border-radius-5 borser-line-1 cou-class-prop-help">       ' );
	buf.append('     <p class="padding-md "><a class="t-check">滴滴滴</a></p>                               ' );
	buf.append('     <p class="padding-md"><a>滴滴滴</a></p>                               ' );
	buf.append('    </div>                                                                 ' );
	buf.append('   </div>                                                                  ' );
	buf.append('   <div class="col-xs-2">                                                  ' );
	buf.append('    <div class="class-teacher-help"></div>                                 ' );
	buf.append('   </div>                                                                  ' );
	buf.append('   <div class="col-xs-5">                                                  ' );
	buf.append('    <div class="padding-md font-size-21 font-weight-bold">                 ' );
	buf.append('     辅导本班                                                              ' );
	buf.append('    </div>                                                                 ' );
	buf.append('    <div class="bg-color-white border-radius-5  borser-line-1 cou-class-prop-help">       ' );
	buf.append('     <p class="padding-md"><a>滴滴滴</a></p>                               ' );
	buf.append('     <p class="padding-md"><a>滴滴滴</a></p>                               ' );
	buf.append('    </div>                                                                 ' );
	buf.append('   </div>                                                                  ' );
	buf.append('  </div>                                                                   ' );
	buf.append('  <div class="container-fluid confirm-div bg-color-class padding-md">      ' );
	buf.append('   <div class="row popup-btn-div conduct-confirm-btn-div">                 ' );
	buf.append('    <span class="btn btn-abj-primary btn-sub"> 保存</span>                      ' );
	buf.append('   </div>                                                                  ' );
	buf.append('  </div> 																	');			

	return buf.toString();

};

HtmlUntil.couClassAdd4Manage = function(data){
	var buf = new StringBuffer();
	
 	buf.append(' <div class="cou-class-manager-tab-stu-model-modify1-div">                  ');
	buf.append('   <div class="row form-popup-md">                                          ');
	buf.append('    <div class="col-xs-6">                                                  ');
	buf.append('     <input class="form-control" type="text" placeholder="计科0302班" />    ');
	buf.append('    </div>                                                                  ');
	buf.append('    <div class="col-xs-6">                                                  ');
	buf.append('     <select class="form-control"><option>计算机</option></select>          ');
	buf.append('    </div>                                                                  ');
	buf.append('   </div>                                                                   ');
	buf.append('   <div class="row form-popup-md">                                          ');
	buf.append('    <div class="col-xs-6">                                                  ');
	buf.append('     <select class="form-control"><option>入学年份</option></select>        ');
	buf.append('    </div>                                                                  ');
	buf.append('    <div class="col-xs-6">                                                  ');
	buf.append('     <select class="form-control"><option>毕业年份</option></select>        ');
	buf.append('    </div>                                                                  ');
	buf.append('   </div>                                                                   ');
	buf.append('   <div class="row form-popup-md">                                          ');
	buf.append('    <textarea class="form-control"></textarea>                              ');
	buf.append('   </div>                                                                   ');
	buf.append('  </div>                                                                    ');
	buf.append('  <div class="container-fluid confirm-div">                                 ');
	buf.append('   <div class="row popup-btn-div conduct-confirm-btn-div">                  ');
	buf.append('    <span class="btn btn-abj-primary btn-sub"> 提交</span>                       ');
	buf.append('   </div>                                                                   ');
	buf.append('  </div> 																	');											
	
	return buf.toString();
};


HtmlUntil.couClassTabStuModelModify4Manage = function(data){
	var buf = new StringBuffer();
	
	buf.append('	<div class="cou-class-manager-tab-stu-model-modify-div">                                                                       ' );
    buf.append('     <div class="row form-popup-md">                                                                                               ' );
    buf.append('      <div class="col-xs-6 row">                                                                                                   ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p><span class="font-color-red">*</span>学号:</p>                                                                                                              ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8">                                                                                                      ' );
    buf.append('        <input class="form-control" type="text" value="2016011111" />                                                              ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('      <div class="col-xs-6">                                                                                                       ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p><span class="font-color-red">*</span>姓名:</p>                                                                                                              ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8">                                                                                                      ' );
    buf.append('        <input class="form-control" type="text" value="周瑜" />                                                                    ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('     </div>                                                                                                                        ' );
    buf.append('     <div class="row form-popup-md">                                                                                               ' );
    buf.append('      <div class="col-xs-6 row">                                                                                                   ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p><span class="font-color-red">*</span>性别:</p>                                                                                                              ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8 modify-sex-select">                                                                                    ' );
    buf.append('        <input type="radio" name="sex" checked="checked" />男                                                                      ' );
    buf.append('        <input type="radio" name="sex" />女                                                                                        ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('      <div class="col-xs-6">                                                                                                       ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p>出生年月:</p>                                                                                                           ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8">                                                                                                      ' );
    buf.append('        <input class="form-control" type="text" value="1991-1-1" />                                                                ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('     </div>                                                                                                                        ' );
    buf.append('     <div class="row form-popup-md">                                                                                               ' );
    buf.append('      <div class="col-xs-6 row">                                                                                                   ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p>民族:</p>                                                                                                               ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8 modify-sex-select">                                                                                    ' );
    buf.append('        <select class="form-control"> <option selected="selected">汉</option> 汉</select>                                          ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('      <div class="col-xs-6">                                                                                                       ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p>政治面貌:</p>                                                                                                           ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8">                                                                                                      ' );
    buf.append('        <input class="form-control" type="text" value="党员" />                                                                    ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('     </div>                                                                                                                        ' );
    buf.append('     <div class="row form-popup-md ">                                                                                              ' );
    buf.append('      <div class="col-xs-2"></div>                                                                                                 ' );
    buf.append('      <div class="col-xs-10 cou-class-manager-tab-stu-model-modify">                                                               ' );
    buf.append('       <input type="checkbox" />贫困生                                                                                             ' );
    buf.append('       <input type="checkbox" />孤残学生                                                                                           ' );
    buf.append('       <input type="checkbox" />单亲家庭                                                                                           ' );
    buf.append('       <input type="checkbox" />烈士子女                                                                                           ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('     </div>                                                                                                                        ' );
    buf.append('     <div class="row form-popup-md">                                                                                               ' );
    buf.append('      <div class="col-xs-6 row">                                                                                                   ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p>身份证:</p>                                                                                                             ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8 modify-sex-select">                                                                                    ' );
    buf.append('        <input class="form-control" type="text" value="510181199101012341" />                                                      ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('      <div class="col-xs-6">                                                                                                       ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p>高考号:</p>                                                                                                             ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8">                                                                                                      ' );
    buf.append('        <input class="form-control" type="text" value="2124123" />                                                                 ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('     </div>                                                                                                                        ' );
    buf.append('     <div class="row form-popup-md">                                                                                               ' );
    buf.append('      <div class="col-xs-6 row">                                                                                                   ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p>手机:</p>                                                                                                               ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8 modify-sex-select">                                                                                    ' );
    buf.append('        <input class="form-control" type="text" value="1870680000" />                                                              ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('      <div class="col-xs-6">                                                                                                       ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p>短号:</p>                                                                                                               ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8">                                                                                                      ' );
    buf.append('        <input class="form-control" type="text" />                                                                                 ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('     </div>                                                                                                                        ' );
    buf.append('     <div class="row form-popup-md">                                                                                               ' );
    buf.append('      <div class="col-xs-6 row">                                                                                                   ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p>QQ号:</p>                                                                                                               ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8 modify-sex-select">                                                                                    ' );
    buf.append('        <input class="form-control" type="text" value="628175" />                                                                  ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('      <div class="col-xs-6">                                                                                                       ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p>家长姓名:</p>                                                                                                           ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8">                                                                                                      ' );
    buf.append('        <input class="form-control" type="text" value="周润发" />                                                                  ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('     </div>                                                                                                                        ' );
    buf.append('     <div class="row form-popup-md">                                                                                               ' );
    buf.append('      <div class="col-xs-6 row">                                                                                                   ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p>邮政编码:</p>                                                                                                           ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8 modify-sex-select">                                                                                    ' );
    buf.append('        <input class="form-control" type="text" />                                                                                 ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('      <div class="col-xs-6">                                                                                                       ' );
    buf.append('       <div class="col-xs-4">                                                                                                      ' );
    buf.append('        <p>家庭经济:</p>                                                                                                           ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('       <div class="col-xs-8">                                                                                                      ' );
    buf.append('        <select class="form-control"></select>                                                                                     ' );
    buf.append('       </div>                                                                                                                      ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('     </div>                                                                                                                        ' );
    buf.append('     <div class="row form-popup-md ">                                                                                              ' );
    buf.append('      <div class="col-xs-2">                                                                                                       ' );
    buf.append('       <p>籍贯:</p>                                                                                                                ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('      <div class="col-xs-10 cou-class-manager-tab-stu-model-modify">                                                               ' );
    buf.append('       <input class="form-control" type="text" style="width:457px;" value="四川成都" />                                            ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('     </div>                                                                                                                        ' );
    buf.append('     <div class="row form-popup-md ">                                                                                              ' );
    buf.append('      <div class="col-xs-2" style="padding-right:14px;">                                                                           ' );
    buf.append('       <p>家庭住址:</p>                                                                                                            ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('      <div class="col-xs-10 cou-class-manager-tab-stu-model-modify">                                                               ' );
    buf.append('       <input class="form-control" type="text" style="width:457px;" value="光华大道6号66" />                                       ' );
    buf.append('      </div>                                                                                                                       ' );
    buf.append('     </div>                                                                                                                        ' );
    buf.append('    </div>                                                                                                                         ' );
    buf.append('    <div class="container-fluid confirm-div">                                                                                      ' );
    buf.append('     <div class="row popup-btn-div conduct-confirm-btn-div">                                                                       ' );
    buf.append('      <span class="btn btn-abj-primary btn-sub"> 提交</span>                                                                            ' );
    buf.append('     </div>                                                                                                                        ' );
    buf.append('    </div> 																															');
    
    return buf.toString();
};
	

HtmlUntil.couClass4propType4Manager = function(data){
	
	var buf = new StringBuffer();
	buf.append(' <div class="container-fluid" style="margin-top:20px" id="cou-class-prop-type-modal">                                                                  ');
	buf.append('  <div class="row padding-md">                                                                                          ');
	buf.append('   <label class="checkbox-inline"> <input type="checkbox" id="inlineCheckbox1" value="贫困学生" /> 贫困学生 </label>    ');
	buf.append('   <label class="checkbox-inline"> <input type="checkbox" id="inlineCheckbox1" value="孤残学生" /> 孤残学生 </label>    ');
	buf.append('   <label class="checkbox-inline"> <input type="checkbox" id="inlineCheckbox1" value="单亲家庭" /> 单亲家庭 </label>    ');
	buf.append('   <label class="checkbox-inline"> <input type="checkbox" id="inlineCheckbox1" value="烈士子女" /> 烈士子女 </label>    ');
	buf.append('  </div>                                                                                                                ');
	buf.append('  <div class="row padding-md">                                                                                          ');
	buf.append('   <label class="checkbox-inline"> <input type="checkbox" id="inlineCheckbox1" value="爱打游戏" /> 爱打游戏 </label>    ');
	buf.append('   <label class="checkbox-inline"> <input type="checkbox" id="inlineCheckbox1" value="家境富有" /> 家境富有 </label>    ');
	buf.append('   <label class="checkbox-inline"> <input type="checkbox" id="inlineCheckbox1" value="性格内向" /> 性格内向 </label>    ');
	buf.append('   <label class="checkbox-inline"> <input type="checkbox" id="inlineCheckbox1" value="其他 	 " /> 其他 </label>         ');
	buf.append('  </div>                                                                                                                ');
	buf.append(' </div>                                                                                                                 ');
	buf.append(' <div class="container-fluid confirm-div">                                                                              ');
	buf.append('  <div class="row popup-btn-div">                                                                                       ');
	buf.append('   <span class="btn btn-abj-primary btn-sub"> 确定</span>                                                               ');
	buf.append('  </div>                                                                                                                ');
	buf.append(' </div> 																												');							
	
	return buf.toString();
};
